[package]
name = "fastobo-py-derive-internal"
version = "0.3.1"
authors = ["Martin Larralde <martin.larralde@ens-cachan.fr>"]
edition = "2018"
publish = false
workspace = ".."

[lib]
proc-macro = true
path = "lib.rs"

[dependencies]
syn = "0.15.44"
quote = "0.6.13"
